# Generated by Django 3.2.8 on 2021-10-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211009_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='names',
        ),
    ]
