# Generated by Django 3.2.8 on 2021-10-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_name_type_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
    ]
